package jii

var Tree []string = []string{
	"{joint-iso-itu-t(2) asn1(1)}",
	"{joint-iso-itu-t(2) association-control(2)}",
	"{joint-iso-itu-t(2) reliable-transfer(3)}",
	"{joint-iso-itu-t(2) remote-operations(4)}",
	"{joint-iso-itu-t(2) ds(5) module(1)}",
	"{joint-iso-itu-t(2) ds(5) serviceElement(2)}",
	"{joint-iso-itu-t(2) ds(5) applicationContext(3)}",
	"{joint-iso-itu-t(2) ds(5) attributeType(4)}",
	"{joint-iso-itu-t(2) ds(5) attributeSyntaxVendor(5)}",
	"{joint-iso-itu-t(2) ds(5) objectClass(6)}",
	"{joint-iso-itu-t(2) ds(5) attribute-set(7)}",
	"{joint-iso-itu-t(2) ds(5) algorithm(8)}",
	"{joint-iso-itu-t(2) ds(5) abstractSyntax(9)}",
	"{joint-iso-itu-t(2) ds(5) object(10)}",
	"{joint-iso-itu-t(2) ds(5) port(11)}",
	"{joint-iso-itu-t(2) ds(5) dsaOperationalAttribute(12)}",
	"{joint-iso-itu-t(2) ds(5) matchingRule(13)}",
	"{joint-iso-itu-t(2) ds(5) knowledgeMatchingRule(14)}",
	"{joint-iso-itu-t(2) ds(5) nameForm(15)}",
	"{joint-iso-itu-t(2) ds(5) group(16)}",
	"{joint-iso-itu-t(2) ds(5) subentry(17)}",
	"{joint-iso-itu-t(2) ds(5) operationalAttributeType(18)}",
	"{joint-iso-itu-t(2) ds(5) operationalBinding(19)}",
	"{joint-iso-itu-t(2) ds(5) schemaObjectClass(20)}",
	"{joint-iso-itu-t(2) ds(5) schemaOperationalAttribute(21)}",
	"{joint-iso-itu-t(2) ds(5) administrativeRole(23)}",
	"{joint-iso-itu-t(2) ds(5) accessControlAttribute(24)}",
	"{joint-iso-itu-t(2) ds(5) rosObjectClass(25)}",
	"{joint-iso-itu-t(2) ds(5) contract(26)}",
	"{joint-iso-itu-t(2) ds(5) package(27)}",
	"{joint-iso-itu-t(2) ds(5) accessControlSchemes(28)}",
	"{joint-iso-itu-t(2) ds(5) certificateExtension(29)}",
	"{joint-iso-itu-t(2) ds(5) managementObject(30)}",
	"{joint-iso-itu-t(2) ds(5) attributeValueContext(31)}",
	"{joint-iso-itu-t(2) ds(5) securityExchange(32)}",
	"{joint-iso-itu-t(2) ds(5) idmProtocol(33)}",
	"{joint-iso-itu-t(2) ds(5) problem(34)}",
	"{joint-iso-itu-t(2) ds(5) notification(35)}",
	"{joint-iso-itu-t(2) ds(5) matchingRestriction(36)}",
	"{joint-iso-itu-t(2) ds(5) controlAttributeType(37)}",
	"{joint-iso-itu-t(2) ds(5) keyPurposes(38)}",
	"{joint-iso-itu-t(2) ds(5) passwordQuality(39)}",
	"{joint-iso-itu-t(2) ds(5) attributeSyntax(40)}",
	"{joint-iso-itu-t(2) ds(5) avRestriction(41)}",
	"{joint-iso-itu-t(2) ds(5) cmsContentType(42)}",
	"{joint-iso-itu-t(2) ds(5) wrprot(43)}",
	"{joint-iso-itu-t(2) ds(5) algo(44)}",
	"{joint-iso-itu-t(2) mhs(6)}",
	"{joint-iso-itu-t(2) ccr(7)}",
	"{joint-iso-itu-t(2) oda(8)}",
	"{joint-iso-itu-t(2) ms(9)}",
	"{joint-iso-itu-t(2) transaction-processing(10)}",
	"{joint-iso-itu-t(2) dor(11)}",
	"{joint-iso-itu-t(2) reference-data-transfer(12)}",
	"{joint-iso-itu-t(2) network-layer(13)}",
	"{joint-iso-itu-t(2) transport-layer(14)}",
	"{joint-iso-itu-t(2) datalink-layer(15)}",
	"{joint-iso-itu-t(2) country(16)}",
	"{joint-iso-itu-t(2) registration-procedures(17)}",
	"{joint-iso-itu-t(2) physical-layer(18)}",
	"{joint-iso-itu-t(2) mheg(19)}",
	"{joint-iso-itu-t(2) genericULS(20)}",
	"{joint-iso-itu-t(2) transport-layer-security-protocol(21)}",
	"{joint-iso-itu-t(2) network-layer-security-protocol(22)}",
	"{joint-iso-itu-t(2) international-organizations(23)}",
	"{joint-iso-itu-t(2) sios(24)}",
	"{joint-iso-itu-t(2) uuid(25) nil(0)}",
	"{joint-iso-itu-t(2) uuid(25) selab(288786655511405443130567505384701230)}",
	"{joint-iso-itu-t(2) uuid(25) ans(987895962269883002155146617097157934)}",
	"{joint-iso-itu-t(2) odp(26)}",
	"{joint-iso-itu-t(2) tag-based(27)}",
	"{joint-iso-itu-t(2) its(28)}",
	"{joint-iso-itu-t(2) upu(40)}",
	"{joint-iso-itu-t(2) bip(41)}",
	"{joint-iso-itu-t(2) telebiometrics(42)}",
	"{joint-iso-itu-t(2) cybersecurity(48)}",
	"{joint-iso-itu-t(2) alerting(49)}",
	"{joint-iso-itu-t(2) ors(50)}",
	"{joint-iso-itu-t(2) gs1(51)}",
	"{joint-iso-itu-t(2) uav(52)}",
}
